[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "conant robotics"
authors = [{name = "Conant Robotics", email = "conantroboticsclub@gmail.com"}]
dynamic = ["version", "description"]
